import { createFileRoute } from "@tanstack/react-router";
import type {} from "@tanstack/react-start";

// TODO: replace with your project URL once a custom domain is attached.
const BASE_URL = "";

interface SitemapEntry {
  path: string;
  changefreq?: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
  priority?: string;
}

const ENTRIES: SitemapEntry[] = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/image-compressor", changefreq: "monthly", priority: "0.9" },
  { path: "/image-resizer", changefreq: "monthly", priority: "0.9" },
  { path: "/image-cropper", changefreq: "monthly", priority: "0.9" },
  { path: "/rotate-flip", changefreq: "monthly", priority: "0.8" },
  { path: "/image-format-converter", changefreq: "monthly", priority: "0.9" },
  { path: "/watermark", changefreq: "monthly", priority: "0.8" },
  { path: "/color-picker", changefreq: "monthly", priority: "0.8" },
  { path: "/images-to-pdf", changefreq: "monthly", priority: "0.9" },
  { path: "/pdf-to-images", changefreq: "monthly", priority: "0.9" },
  { path: "/qr-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/password-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/json-formatter", changefreq: "monthly", priority: "0.9" },
  { path: "/base64", changefreq: "monthly", priority: "0.9" },
  { path: "/text-case-converter", changefreq: "monthly", priority: "0.9" },
  { path: "/exif-viewer", changefreq: "monthly", priority: "0.8" },
  { path: "/favicon-generator", changefreq: "monthly", priority: "0.8" },
  { path: "/jwt-decoder", changefreq: "monthly", priority: "0.9" },
  { path: "/regex-tester", changefreq: "monthly", priority: "0.9" },
  { path: "/diff-checker", changefreq: "monthly", priority: "0.9" },
  { path: "/heic-to-jpg", changefreq: "monthly", priority: "0.9" },
  { path: "/pdf-merge", changefreq: "monthly", priority: "0.9" },
  { path: "/pdf-split", changefreq: "monthly", priority: "0.9" },
  { path: "/word-counter", changefreq: "monthly", priority: "0.9" },
  { path: "/hash-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/uuid-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/url-encoder", changefreq: "monthly", priority: "0.9" },
  { path: "/lorem-ipsum", changefreq: "monthly", priority: "0.9" },
  { path: "/timestamp-converter", changefreq: "monthly", priority: "0.9" },
  { path: "/markdown-preview", changefreq: "monthly", priority: "0.9" },
  { path: "/csv-json", changefreq: "monthly", priority: "0.9" },
  { path: "/color-converter", changefreq: "monthly", priority: "0.9" },
  { path: "/slug-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/number-base-converter", changefreq: "monthly", priority: "0.9" },
  { path: "/html-entities", changefreq: "monthly", priority: "0.9" },
  { path: "/text-to-pdf", changefreq: "monthly", priority: "0.9" },
  { path: "/pdf-page-numbers", changefreq: "monthly", priority: "0.9" },
  { path: "/random-number", changefreq: "monthly", priority: "0.9" },
  { path: "/color-palette", changefreq: "monthly", priority: "0.9" },
  { path: "/line-tools", changefreq: "monthly", priority: "0.9" },
  { path: "/text-extractor", changefreq: "monthly", priority: "0.9" },
  { path: "/gradient-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/markdown-to-pdf", changefreq: "monthly", priority: "0.9" },
  { path: "/pdf-rotate", changefreq: "monthly", priority: "0.9" },
  { path: "/pdf-extract-text", changefreq: "monthly", priority: "0.9" },
  { path: "/photo-filters", changefreq: "monthly", priority: "0.9" },
  { path: "/image-to-base64", changefreq: "monthly", priority: "0.9" },
  { path: "/pdf-delete-pages", changefreq: "monthly", priority: "0.9" },
  { path: "/pdf-extract-pages", changefreq: "monthly", priority: "0.9" },
  { path: "/box-shadow", changefreq: "monthly", priority: "0.9" },
  { path: "/cron-parser", changefreq: "monthly", priority: "0.9" },
  { path: "/age-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/bmi-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/percentage-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/loan-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/tip-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/discount-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/unit-converter", changefreq: "monthly", priority: "0.9" },
  { path: "/temperature-converter", changefreq: "monthly", priority: "0.9" },
  { path: "/roman-numerals", changefreq: "monthly", priority: "0.9" },
  { path: "/text-reverser", changefreq: "monthly", priority: "0.9" },
  { path: "/morse-code", changefreq: "monthly", priority: "0.9" },
  { path: "/binary-translator", changefreq: "monthly", priority: "0.9" },
  { path: "/email-validator", changefreq: "monthly", priority: "0.9" },
  { path: "/stopwatch-timer", changefreq: "monthly", priority: "0.9" },
  { path: "/dice-roller", changefreq: "monthly", priority: "0.9" },
  { path: "/coin-flip", changefreq: "monthly", priority: "0.9" },
  { path: "/list-randomizer", changefreq: "monthly", priority: "0.9" },
  { path: "/contrast-checker", changefreq: "monthly", priority: "0.9" },
  { path: "/border-radius", changefreq: "monthly", priority: "0.9" },
  { path: "/date-difference", changefreq: "monthly", priority: "0.9" },
  { path: "/compound-interest", changefreq: "monthly", priority: "0.9" },
  { path: "/youtube-thumbnail", changefreq: "monthly", priority: "0.9" },
  { path: "/text-to-speech", changefreq: "monthly", priority: "0.9" },
  { path: "/svg-to-png", changefreq: "monthly", priority: "0.9" },
  { path: "/pomodoro", changefreq: "monthly", priority: "0.9" },
  { path: "/meta-tag-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/robots-txt-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/ascii-art", changefreq: "monthly", priority: "0.9" },
  { path: "/color-blindness", changefreq: "monthly", priority: "0.9" },
  { path: "/screen-recorder", changefreq: "monthly", priority: "0.9" },
  { path: "/tally-counter", changefreq: "monthly", priority: "0.9" },
  { path: "/speech-to-text", changefreq: "monthly", priority: "0.9" },
  { path: "/webcam-capture", changefreq: "monthly", priority: "0.9" },
  { path: "/audio-recorder", changefreq: "monthly", priority: "0.9" },
  { path: "/pig-latin", changefreq: "monthly", priority: "0.9" },
  { path: "/fancy-text", changefreq: "monthly", priority: "0.9" },
  { path: "/wingdings", changefreq: "monthly", priority: "0.9" },
  { path: "/aspect-ratio", changefreq: "monthly", priority: "0.9" },
  { path: "/nato-phonetic", changefreq: "monthly", priority: "0.9" },
  { path: "/chmod-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/sql-formatter", changefreq: "monthly", priority: "0.9" },
  { path: "/xml-formatter", changefreq: "monthly", priority: "0.9" },
  { path: "/gpa-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/binary-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/resistor-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/fraction-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/scientific-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/subnet-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/barcode-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/qr-reader", changefreq: "monthly", priority: "0.9" },
  { path: "/clip-path-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/user-agent-parser", changefreq: "monthly", priority: "0.9" },
  { path: "/ig-grid-splitter", changefreq: "monthly", priority: "0.9" },
  { path: "/ig-carousel-splitter", changefreq: "monthly", priority: "0.9" },
  { path: "/ig-photo-resizer", changefreq: "monthly", priority: "0.9" },
  { path: "/ig-hashtag-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/ig-bio-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/ig-engagement-rate", changefreq: "monthly", priority: "0.9" },
  { path: "/ig-line-break", changefreq: "monthly", priority: "0.9" },
  { path: "/ig-highlight-cover", changefreq: "monthly", priority: "0.9" },
  { path: "/ig-reels-cover", changefreq: "monthly", priority: "0.9" },
  { path: "/ig-username-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/yt-video-id", changefreq: "monthly", priority: "0.9" },
  { path: "/yt-embed-code", changefreq: "monthly", priority: "0.9" },
  { path: "/yt-timestamp", changefreq: "monthly", priority: "0.9" },
  { path: "/yt-title-counter", changefreq: "monthly", priority: "0.9" },
  { path: "/yt-hashtag-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/yt-subscribe-link", changefreq: "monthly", priority: "0.9" },
  { path: "/yt-money-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/yt-comment-picker", changefreq: "monthly", priority: "0.9" },
  { path: "/yt-chapters", changefreq: "monthly", priority: "0.9" },
  { path: "/yt-tag-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/yt-banner-maker", changefreq: "monthly", priority: "0.9" },
  { path: "/mortgage-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/emoji-picker", changefreq: "monthly", priority: "0.9" },
  { path: "/json-minifier", changefreq: "monthly", priority: "0.9" },
  { path: "/image-to-base64", changefreq: "monthly", priority: "0.9" },
  { path: "/reading-time", changefreq: "monthly", priority: "0.9" },
  { path: "/readability-score", changefreq: "monthly", priority: "0.9" },
  { path: "/sort-lines", changefreq: "monthly", priority: "0.9" },
  { path: "/dedupe-lines", changefreq: "monthly", priority: "0.9" },
  { path: "/strip-html", changefreq: "monthly", priority: "0.9" },
  { path: "/repeat-text", changefreq: "monthly", priority: "0.9" },
  { path: "/find-replace", changefreq: "monthly", priority: "0.9" },
  { path: "/strip-whitespace", changefreq: "monthly", priority: "0.9" },
  { path: "/add-line-numbers", changefreq: "monthly", priority: "0.9" },
  { path: "/acronym-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/sleep-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/time-card-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/date-add-subtract", changefreq: "monthly", priority: "0.9" },
  { path: "/pace-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/calorie-burn", changefreq: "monthly", priority: "0.9" },
  { path: "/macro-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/body-fat-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/ideal-weight", changefreq: "monthly", priority: "0.9" },
  { path: "/due-date-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/ovulation-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/ip-validator", changefreq: "monthly", priority: "0.9" },
  { path: "/cidr-range", changefreq: "monthly", priority: "0.9" },
  { path: "/mac-lookup", changefreq: "monthly", priority: "0.9" },
  { path: "/dns-format", changefreq: "monthly", priority: "0.9" },
  { path: "/spf-builder", changefreq: "monthly", priority: "0.9" },
  { path: "/dmarc-builder", changefreq: "monthly", priority: "0.9" },
  { path: "/dkim-keygen", changefreq: "monthly", priority: "0.9" },
  { path: "/port-lookup", changefreq: "monthly", priority: "0.9" },
  { path: "/http-status", changefreq: "monthly", priority: "0.9" },
  { path: "/url-parser", changefreq: "monthly", priority: "0.9" },
  { path: "/reverse-dns", changefreq: "monthly", priority: "0.9" },
  { path: "/exif-batch-strip", changefreq: "monthly", priority: "0.9" },
  { path: "/face-blur", changefreq: "monthly", priority: "0.9" },
  { path: "/pdf-redact", changefreq: "monthly", priority: "0.9" },
  { path: "/filename-sanitizer", changefreq: "monthly", priority: "0.9" },
  { path: "/email-alias", changefreq: "monthly", priority: "0.9" },
  { path: "/audio-trimmer", changefreq: "monthly", priority: "0.9" },
  { path: "/audio-merger", changefreq: "monthly", priority: "0.9" },
  { path: "/audio-converter", changefreq: "monthly", priority: "0.9" },
  { path: "/audio-speed", changefreq: "monthly", priority: "0.9" },
  { path: "/audio-pitch", changefreq: "monthly", priority: "0.9" },
  { path: "/audio-reverser", changefreq: "monthly", priority: "0.9" },
  { path: "/audio-normalizer", changefreq: "monthly", priority: "0.9" },
  { path: "/audio-crossfade", changefreq: "monthly", priority: "0.9" },
  { path: "/silence-remover", changefreq: "monthly", priority: "0.9" },
  { path: "/tone-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/metronome", changefreq: "monthly", priority: "0.9" },
  { path: "/bpm-detector", changefreq: "monthly", priority: "0.9" },
  { path: "/audio-visualizer", changefreq: "monthly", priority: "0.9" },
  { path: "/ringtone-maker", changefreq: "monthly", priority: "0.9" },
  { path: "/bitcoin-address-validator", changefreq: "monthly", priority: "0.9" },
  { path: "/eth-address-checker", changefreq: "monthly", priority: "0.9" },
  { path: "/gas-unit-converter", changefreq: "monthly", priority: "0.9" },
  { path: "/wallet-qr-code", changefreq: "monthly", priority: "0.9" },
  { path: "/solidity-function-selector", changefreq: "monthly", priority: "0.9" },
  { path: "/dyslexia-text-preview", changefreq: "monthly", priority: "0.9" },
  { path: "/bionic-text", changefreq: "monthly", priority: "0.9" },
  { path: "/font-size-tester", changefreq: "monthly", priority: "0.9" },
  { path: "/color-blindness-simulator", changefreq: "monthly", priority: "0.9" },
  { path: "/world-clock", changefreq: "monthly", priority: "0.9" },
  { path: "/distance-calculator", changefreq: "monthly", priority: "0.9" },
  { path: "/trip-cost-splitter", changefreq: "monthly", priority: "0.9" },
  { path: "/invoice-generator", changefreq: "monthly", priority: "0.9" },
  { path: "/resume-builder", changefreq: "monthly", priority: "0.9" },
  { path: "/periodic-table", changefreq: "monthly", priority: "0.8" },
  { path: "/flash-cards", changefreq: "monthly", priority: "0.8" },
  { path: "/multiplication-table", changefreq: "monthly", priority: "0.8" },
  { path: "/wheel-of-names", changefreq: "monthly", priority: "0.9" },
  { path: "/sudoku", changefreq: "monthly", priority: "0.9" },
  { path: "/mnemonic-generator", changefreq: "monthly", priority: "0.8" },
];


export const Route = createFileRoute("/sitemap.xml")({
  server: {
    handlers: {
      GET: async () => {
        const urls = ENTRIES.map((e) =>
          [
            `  <url>`,
            `    <loc>${BASE_URL}${e.path}</loc>`,
            e.changefreq ? `    <changefreq>${e.changefreq}</changefreq>` : null,
            e.priority ? `    <priority>${e.priority}</priority>` : null,
            `  </url>`,
          ]
            .filter(Boolean)
            .join("\n"),
        );

        const xml = [
          `<?xml version="1.0" encoding="UTF-8"?>`,
          `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
          ...urls,
          `</urlset>`,
        ].join("\n");

        return new Response(xml, {
          headers: {
            "Content-Type": "application/xml",
            "Cache-Control": "public, max-age=3600",
          },
        });
      },
    },
  },
});
